#this program is an online vendor program that calculates the final price
print("Hello customer!.")
print("What do you want to spend your wallet on?")
print("We have 6 items that are in stock.")
print("The following items are!: ")
print(" ")
print("Suitcase = $20.50")
print("Swiss Army Knife = $10.50")
print("Paraglider = $50.25")
print("Soccer ball = $5.25")
print("Jumprope = $15.50")
print("Chocolate Bar = $5.05")
print(" ")
print("Find anything you like? Don't hesitate to buy!")
print(" ")
GST = float(0.17)
Suitcase = float(20.50)
SwissArmyKnife = float(10.50)
Paraglider = float(50.25)
Soccerball = float(5.25)
Jumprope = float(15.50)
ChocoBar = float(5.05)

Suitcase_Purchases = int(input("Please enter how many suitcases you want to purchase: "))
SwissArmyKnife_Purchases = int(input("Please enter how many swiss army knives you want to purchase: "))
Paraglider_Purchases = int(input("Please enter how many Paragliders you want to purchase: "))
Soccerball_Purchases = int(input("Please enter how many soccer balls you want to purchase: "))
Jumprope_Purchases = int(input("Please enter how many Jumprope you want to purchase: "))
ChocoBar_Purchases = int(input("Last but not least, please enter how many chocolate bars you want to purchase: "))

Finalprice = ((Suitcase*Suitcase_Purchases)+(SwissArmyKnife*SwissArmyKnife_Purchases)+(Paraglider*Paraglider_Purchases)+(Soccerball*Soccerball_Purchases)+(Jumprope*Jumprope_Purchases)+(ChocoBar*ChocoBar_Purchases))

print(" ")
print("Your final price!: $", round(Finalprice, 2))
print(" ")
print("We hope you come back soon!")